In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('MergedDataset.csv')
responses = pd.read_csv('Responses.csv')
scores = pd.read_csv('Scores.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Question     358 non-null    object
 1   Answer       358 non-null    object
 2   Response1    0 non-null      float64
 3   Response2    0 non-null      float64
 4   Response3    0 non-null      float64
 5   Response4    0 non-null      float64
 6   Response5    0 non-null      float64
 7   Response5.1  0 non-null      float64
 8   Response6    0 non-null      float64
 9   Response6.1  0 non-null      float64
 10  Response7    0 non-null      float64
 11  Response8    0 non-null      float64
 12  Response8.1  0 non-null      float64
 13  Response9    0 non-null      float64
 14  Response10   0 non-null      float64
dtypes: float64(13), object(2)
memory usage: 42.1+ KB

In [ ]:
df = df[['Question','Answer']]

In [ ]:
df

,Question,Answer
0,What is data science?,Data science is an interdisciplinary field tha...
1,What are the key steps in the data science pro...,The key steps typically include problem defini...
2,What is the difference between supervised and ...,Supervised learning involves training a model ...
3,Explain the bias-variance tradeoff.,The bias-variance tradeoff is the balance betw...
4,What is feature engineering?,Feature engineering is the process of selectin...
...,...,...
353,What is the role of rewards in reinforcement l...,Rewards in reinforcement learning serve as sig...
354,What is the policy gradient in reinforcement l...,The policy gradient is a method used to update...
355,What is the advantage of deep reinforcement le...,Deep reinforcement learning combines the benef...
356,What are some applications of reinforcement le...,Reinforcement learning is applied in various d...
357,What is policy search in reinforcement learning?,Policy search is a reinforcement learning appr...

In [ ]:
df = df[:301]

In [ ]:
df

,Question,Answer
0,What is data science?,Data science is an interdisciplinary field tha...
1,What are the key steps in the data science pro...,The key steps typically include problem defini...
2,What is the difference between supervised and ...,Supervised learning involves training a model ...
3,Explain the bias-variance tradeoff.,The bias-variance tradeoff is the balance betw...
4,What is feature engineering?,Feature engineering is the process of selectin...
...,...,...
296,What are the common density estimation techniq...,Common techniques include histogram-based meth...
297,What is the Gaussian Mixture Model (GMM)?,Gaussian Mixture Model (GMM) is a probabilisti...
298,What is the Expectation-Maximization (EM) algo...,The Expectation-Maximization (EM) algorithm is...
299,What is the difference between generative and ...,Generative models learn the joint probability ...
300,What is the purpose of generative modeling?,Generative modeling is used to model the under...

In [ ]:
responses

,Unnamed: 0,Question,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10
0,0,What is data science?,Data science is a field that combines statisti...,Data science is about using tools like Excel a...,Data science is the process of analyzing large...,I think data science is related to computer sc...,Data science involves machine learning and AI....,Data science is a career where people code a l...,"In my opinion, data science is only about crea...",Data science helps companies to understand cus...,It is a branch of computer science that teache...,Data science is an interdisciplinary field tha...
1,1,What are the key steps in the data science pro...,The key steps in the data science process incl...,"First, you collect some data and then directly...","The process starts with defining the problem, ...",Data science mainly involves writing Python co...,"Key steps include data acquisition, preprocess...",The data science process begins with gathering...,"To do data science, you just need to collect s...","First, you identify a problem. Then you gather...","In data science, you start with a hypothesis, ...",Data science has several steps like understand...
2,2,What is the difference between supervised and ...,Supervised learning uses labeled data to train...,"In supervised learning, the system is told wha...",Supervised learning is when we give the algori...,Supervised learning is used in games while uns...,Supervised learning models are trained on labe...,I think supervised learning is when you use ma...,"In supervised learning, the machine learns fro...",The key difference is that supervised learning...,Supervised learning includes algorithms like l...,Supervised learning is for prediction problems...
3,3,Explain the bias-variance tradeoff.,The bias-variance tradeoff is a concept in mac...,Bias happens when a model makes strong assumpt...,I think bias is when a model always gives the ...,Bias-variance tradeoff is about choosing betwe...,Bias is always good because it helps the model...,The bias-variance tradeoff is like choosing be...,Bias is a kind of error that makes a model ver...,Bias and variance are both types of errors in ...,This tradeoff refers to the challenge of balan...,I believe bias is like a mistake in the coding...
4,4,What is feature engineering?,Feature engineering is the process of creating...,"In feature engineering, we clean the dataset a...",Feature engineering is a critical step in data...,Feature engineering is basically when you take...,It’s a technique to prepare input data before ...,"In my understanding, feature engineering means...",Feature engineering helps convert data into a ...,It is the science of selecting the right label...,"Feature engineering involves transforming, cre...",I think feature engineering is similar to data...
...,...,...,...,...,...,...,...,...,...,...,...,...
296,296,What are the common density estimation techniq...,Common techniques include parametric methods l...,K-means clustering and DBSCAN are common densi...,Histogram-based methods are simple density est...,Neural networks are widely used for density es...,Kernel Density Estimation smooths data using a...,Density estimation requires labeled data to se...,Gaussian Mixture Models assume data is generat...,Principal Component Analysis is a common densi...,Parametric methods assume a specific form for ...,Decision trees are commonly used density estim...
297,297,What is the Gaussian Mixture Model (GMM)?,Gaussian Mixture Model is a probabilistic mode...,GMM is used for clustering by estimating the p...,It can model complex distributions by combinin...,GMM is a supervised learning method that requi...,Each Gaussian component in the mixture represe...,GMM assumes that all data points are independe...,It's used in applications like image segmentat...,GMM works by fitting a linear regression model...,It estimates cluster membership probabilities ...,GMM is faster than K-means because it uses few...
298,298,What is the Expectation-Maximization (EM) algo...,The EM algorithm is an iterative method to fin...,"It alternates between an expectation step, whi...","EM is commonly used in clustering, such as est...",The algorithm guarantees convergence to the gl...,EM can handle incomplete data by estimating mi...,It works only for linear regression problems w...,The maximization step improves parameter estim...,EM is used in deep learning for training neura...,The algorithm is slow because it requires comp...,EM is especially useful when direct optimizati...
299,299,What is the difference between generative and ...,Generative models learn the joint probability ...,Discriminative models are used only for regres...,Generative models try to model how data is gen...,Discriminative models include algorithms like ...,Generative models are always better than discr...,Discriminative models require more training da...,Generative models can be used for unsupervised...,Discriminative models directly estimate the de...,Generative models simulate data samples but ca...,The main difference is that discriminative mod...
300,300,What is the purpose of generative modeling?,Generative modeling aims to learn the underlyi...,It is mainly used to create fake data for test...,Generative models help in unsupervised learnin...,They are used for data augmentation to improve...,Generative modeling predicts labels from input...,These models are important in applications lik...,Generative models only work with numerical dat...,They can be used to detect anomalies by identi...,The purpose is to compress data by reducing it...,Generative modeling focuses on discriminating ...

In [ ]:
scores

,Unnamed: 0,Question,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10
0,0,What is data science?,1.00,0.30,0.95,0.2,0.40,0.90,0.35,0.85,0.30,1.00
1,1,What are the key steps in the data science pro...,0.95,0.30,1.00,0.2,0.85,0.95,0.40,1.00,0.25,0.95
2,2,What is the difference between supervised and ...,1.00,0.80,0.90,0.4,0.95,0.30,1.00,0.95,0.90,0.70
3,3,Explain the bias-variance tradeoff.,1.00,0.95,0.75,0.9,0.20,0.90,0.30,0.85,0.95,0.40
4,4,What is feature engineering?,1.00,0.30,0.95,0.2,0.90,0.40,0.95,0.25,1.00,0.35
...,...,...,...,...,...,...,...,...,...,...,...,...
296,296,What are the common density estimation techniq...,1.00,0.20,1.00,0.3,1.00,0.20,1.00,0.20,1.00,0.10
297,297,What is the Gaussian Mixture Model (GMM)?,1.00,1.00,1.00,0.2,1.00,0.30,1.00,0.20,1.00,0.40
298,298,What is the Expectation-Maximization (EM) algo...,1.00,1.00,1.00,0.3,1.00,0.10,1.00,0.20,0.30,1.00
299,299,What is the difference between generative and ...,1.00,0.20,1.00,1.0,0.20,0.40,0.30,1.00,0.20,0.30
300,300,What is the purpose of generative modeling?,1.00,0.40,1.00,1.0,0.20,1.00,0.20,1.00,0.30,0.20

In [ ]:
responses_long = responses.melt(id_vars=["Question"],
                  value_vars=["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10"],
                  var_name="Response_Number",
                  value_name="Response")

In [ ]:
responses_long

,Question,Response_Number,Response
0,What is data science?,R1,Data science is a field that combines statisti...
1,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...
2,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...
3,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...
4,What is feature engineering?,R1,Feature engineering is the process of creating...
...,...,...,...
3005,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...
3006,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...
3007,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...
3008,What is the difference between generative and ...,R10,The main difference is that discriminative mod...
3009,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...

In [ ]:
responses_long.head(20)

,Question,Response_Number,Response
0,What is data science?,R1,Data science is a field that combines statisti...
1,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...
2,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...
3,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...
4,What is feature engineering?,R1,Feature engineering is the process of creating...
5,How do you handle missing data in a dataset?,R1,Handling missing data depends on the type and ...
6,What is cross-validation?,R1,Cross-validation is a model evaluation techniq...
7,Explain the concept of overfitting.,R1,Overfitting happens when a machine learning mo...
8,What are some common algorithms used in superv...,R1,Some common supervised learning algorithms inc...
9,What is dimensionality reduction?,R1,Dimensionality reduction is the process of red...
10,What is regularization in machine learning?,R1,Regularization is a technique used in machine ...
11,What is ensemble learning?,R1,Ensemble learning is a machine learning techni...
12,What is the ROC curve?,R1,The ROC (Receiver Operating Characteristic) cu...
13,What is AUC-ROC?,R1,AUC-ROC stands for Area Under the Receiver Ope...
14,What is the difference between classification ...,R1,Classification and regression are types of sup...
15,What is clustering?,R1,Clustering is an unsupervised learning techniq...
16,What is the curse of dimensionality?,R1,The curse of dimensionality refers to the prob...
17,What is the difference between precision and r...,R1,Precision is the ratio of correctly predicted ...
18,What is the F1 score?,R1,The F1 score is the harmonic mean of precision...
19,What is the bias of an estimator?,R1,The bias of an estimator is the difference bet...

In [ ]:
scores_long = scores.melt(id_vars=["Question"],
                  value_vars=["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10"],
                  var_name="Response_Number",
                  value_name="Score")

In [ ]:
scores_long

                                               Question Response_Number  Score
0                                 What is data science?              R1   1.00
1     What are the key steps in the data science pro...              R1   0.95
2     What is the difference between supervised and ...              R1   1.00
3                   Explain the bias-variance tradeoff.              R1   1.00
4                          What is feature engineering?              R1   1.00
...                                                 ...             ...    ...
3005  What are the common density estimation techniq...             R10   0.10
3006          What is the Gaussian Mixture Model (GMM)?             R10   0.40
3007  What is the Expectation-Maximization (EM) algo...             R10   1.00
3008  What is the difference between generative and ...             R10   0.30
3009        What is the purpose of generative modeling?             R10   0.20

[3010 rows x 3 columns]

In [ ]:
scores_long.head(20)

                                             Question Response_Number  Score
0                               What is data science?              R1   1.00
1   What are the key steps in the data science pro...              R1   0.95
2   What is the difference between supervised and ...              R1   1.00
3                 Explain the bias-variance tradeoff.              R1   1.00
4                        What is feature engineering?              R1   1.00
5        How do you handle missing data in a dataset?              R1   1.00
6                           What is cross-validation?              R1   1.00
7                 Explain the concept of overfitting.              R1   1.00
8   What are some common algorithms used in superv...              R1   1.00
9                   What is dimensionality reduction?              R1   1.00
10        What is regularization in machine learning?              R1   1.00
11                         What is ensemble learning?              R1   1.00
12                             What is the ROC curve?              R1   1.00
13                                   What is AUC-ROC?              R1   1.00
14  What is the difference between classification ...              R1   1.00
15                                What is clustering?              R1   1.00
16               What is the curse of dimensionality?              R1   1.00
17  What is the difference between precision and r...              R1   1.00
18                              What is the F1 score?              R1   1.00
19                  What is the bias of an estimator?              R1   1.00

In [ ]:
responses_df = responses_long.drop_duplicates(subset=["Question", "Response_Number"])
scores_df = scores_long.drop_duplicates(subset=["Question", "Response_Number"])

In [ ]:
responses_df

,Question,Response_Number,Response
0,What is data science?,R1,Data science is a field that combines statisti...
1,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...
2,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...
3,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...
4,What is feature engineering?,R1,Feature engineering is the process of creating...
...,...,...,...
3005,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...
3006,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...
3007,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...
3008,What is the difference between generative and ...,R10,The main difference is that discriminative mod...
3009,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...

In [ ]:
responses_df['Response_Number'].value_counts()

Response_Number
R1     262
R2     262
R3     262
R4     262
R5     262
R6     262
R7     262
R8     262
R9     262
R10    262
Name: count, dtype: int64

In [ ]:
scores_df['Response_Number'].value_counts()

Response_Number
R1     262
R2     262
R3     262
R4     262
R5     262
R6     262
R7     262
R8     262
R9     262
R10    262
Name: count, dtype: int64

In [ ]:
merged_df = pd.merge(responses_df, scores_df, on=["Question", "Response_Number"])

In [ ]:
responses_df

,Question,Response_Number,Response
0,What is data science?,R1,Data science is a field that combines statisti...
1,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...
2,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...
3,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...
4,What is feature engineering?,R1,Feature engineering is the process of creating...
...,...,...,...
3005,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...
3006,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...
3007,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...
3008,What is the difference between generative and ...,R10,The main difference is that discriminative mod...
3009,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...

In [ ]:
merged_df

,Question,Response_Number,Response,Score
0,What is data science?,R1,Data science is a field that combines statisti...,1.00
1,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...,0.95
2,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...,1.00
3,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...,1.00
4,What is feature engineering?,R1,Feature engineering is the process of creating...,1.00
...,...,...,...,...
2615,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...,0.10
2616,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...,0.40
2617,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...,1.00
2618,What is the difference between generative and ...,R10,The main difference is that discriminative mod...,0.30
2619,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...,0.20

In [ ]:
print("Duplicate rows in responses:", responses_df.duplicated(subset=["Question", "Response_Number"]).sum())
print("Duplicate rows in scores:", scores_df.duplicated(subset=["Question", "Response_Number"]).sum())
print("Duplicate rows in Merged DF:", merged_df.duplicated(subset=["Question", "Response_Number"]).sum())

Duplicate rows in responses: 0
Duplicate rows in scores: 0
Duplicate rows in Merged DF: 0

In [ ]:
merged_df

,Question,Response_Number,Response,Score
0,What is data science?,R1,Data science is a field that combines statisti...,1.00
1,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...,0.95
2,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...,1.00
3,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...,1.00
4,What is feature engineering?,R1,Feature engineering is the process of creating...,1.00
...,...,...,...,...
2615,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...,0.10
2616,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...,0.40
2617,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...,1.00
2618,What is the difference between generative and ...,R10,The main difference is that discriminative mod...,0.30
2619,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...,0.20

In [ ]:
# Merge correct answers into the long-form dataframe
final_df = pd.merge(merged_df, df, on="Question", how="left")

In [ ]:
final_df

,Question,Response_Number,Response,Score,Answer
0,What is data science?,R1,Data science is a field that combines statisti...,1.00,Data science is an interdisciplinary field tha...
1,What is data science?,R1,Data science is a field that combines statisti...,1.00,Data science is an interdisciplinary field tha...
2,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...,0.95,The key steps typically include problem defini...
3,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...,1.00,Supervised learning involves training a model ...
4,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...,1.00,"In supervised learning, the model is trained o..."
...,...,...,...,...,...
3005,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...,0.10,Common techniques include histogram-based meth...
3006,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...,0.40,Gaussian Mixture Model (GMM) is a probabilisti...
3007,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...,1.00,The Expectation-Maximization (EM) algorithm is...
3008,What is the difference between generative and ...,R10,The main difference is that discriminative mod...,0.30,Generative models learn the joint probability ...
3009,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...,0.20,Generative modeling is used to model the under...

In [ ]:
print("Duplicate rows in Final DF:", final_df.duplicated(subset=["Question", "Response_Number"]).sum())

Duplicate rows in Final DF: 390

In [ ]:
final_df = final_df.drop_duplicates(subset=["Question", "Response_Number"])

In [ ]:
print("Duplicate rows in Final DF:", final_df.duplicated(subset=["Question", "Response_Number"]).sum())

Duplicate rows in Final DF: 0

In [ ]:
final_df['Response_Number'].value_counts()

Response_Number
R1     262
R2     262
R3     262
R4     262
R5     262
R6     262
R7     262
R8     262
R9     262
R10    262
Name: count, dtype: int64

In [ ]:
final_df

,Question,Response_Number,Response,Score,Answer
0,What is data science?,R1,Data science is a field that combines statisti...,1.00,Data science is an interdisciplinary field tha...
2,What are the key steps in the data science pro...,R1,The key steps in the data science process incl...,0.95,The key steps typically include problem defini...
3,What is the difference between supervised and ...,R1,Supervised learning uses labeled data to train...,1.00,Supervised learning involves training a model ...
5,Explain the bias-variance tradeoff.,R1,The bias-variance tradeoff is a concept in mac...,1.00,The bias-variance tradeoff is the balance betw...
6,What is feature engineering?,R1,Feature engineering is the process of creating...,1.00,Feature engineering is the process of selectin...
...,...,...,...,...,...
3005,What are the common density estimation techniq...,R10,Decision trees are commonly used density estim...,0.10,Common techniques include histogram-based meth...
3006,What is the Gaussian Mixture Model (GMM)?,R10,GMM is faster than K-means because it uses few...,0.40,Gaussian Mixture Model (GMM) is a probabilisti...
3007,What is the Expectation-Maximization (EM) algo...,R10,EM is especially useful when direct optimizati...,1.00,The Expectation-Maximization (EM) algorithm is...
3008,What is the difference between generative and ...,R10,The main difference is that discriminative mod...,0.30,Generative models learn the joint probability ...
3009,What is the purpose of generative modeling?,R10,Generative modeling focuses on discriminating ...,0.20,Generative modeling is used to model the under...

In [ ]:
final_df.to_csv('Final_df.csv',index=False)